name: gd
description: A command line interface to setup your environment to work with Godot sources and GDExtensions.
version: 0.1.0
repository: https://github.com/poirierlouis/godot_cli
issue_tracker: https://github.com/poirierlouis/godot_cli/issues
funding: https://www.buymeacoffee.com/lpfreelance

executables:
  gd:

platforms:
  windows
# linux
# macos

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.0
  path: ^1.8.3
